In [1]:
import pandas as pd

In [4]:
cars = pd.read_csv("../datasets/cars.csv")

In [3]:
cars.head()

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0

In [5]:
cars.tail()

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
2054,Mahindra,XUV500 W8 [2015-2017],850000,2016,90300,Diesel,Manual,Surat,White,First,Individual,2179 cc,138 bhp @ 3750 rpm,330 Nm @ 1600 rpm,FWD,4585.0,1890.0,1785.0,7.0,70.0
2055,Hyundai,Eon D-Lite +,275000,2014,83000,Petrol,Manual,Ahmedabad,White,Second,Individual,814 cc,55 bhp @ 5500 rpm,75 Nm @ 4000 rpm,FWD,3495.0,1550.0,1500.0,5.0,32.0
2056,Ford,Figo Duratec Petrol ZXI 1.2,240000,2013,73000,Petrol,Manual,Thane,Silver,First,Individual,1196 cc,70 bhp @ 6250 rpm,102 Nm @ 4000 rpm,FWD,3795.0,1680.0,1427.0,5.0,45.0
2057,BMW,5-Series 520d Luxury Line [2017-2019],4290000,2018,60474,Diesel,Automatic,Coimbatore,White,First,Individual,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,RWD,4936.0,1868.0,1479.0,5.0,65.0
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],670000,2017,72000,Diesel,Manual,Guwahati,White,First,Individual,1493 cc,70 bhp @ 3600 rpm,195 Nm @ 1400 rpm,RWD,3995.0,1745.0,1880.0,7.0,NaN

In [6]:
cars.Price

0        505000
1        450000
2        220000
3        799000
4       1950000
         ...
2054     850000
2055     275000
2056     240000
2057    4290000
2058     670000
Name: Price, Length: 2059, dtype: int64

In [7]:
cars.Year

0       2017
1       2014
2       2011
3       2019
4       2018
        ...
2054    2016
2055    2014
2056    2013
2057    2018
2058    2017
Name: Year, Length: 2059, dtype: int64

In [8]:
cars[["Price","Year"]]

        Price  Year
0      505000  2017
1      450000  2014
2      220000  2011
3      799000  2019
4     1950000  2018
...       ...   ...
2054   850000  2016
2055   275000  2014
2056   240000  2013
2057  4290000  2018
2058   670000  2017

[2059 rows x 2 columns]

In [9]:
cars.Year>2018

0       False
1       False
2       False
3        True
4       False
        ...
2054    False
2055    False
2056    False
2057    False
2058    False
Name: Year, Length: 2059, dtype: bool

In [10]:
(cars.Year>2018).sum()

587

In [12]:
(~(cars.Year>2018)).sum()

1472

In [13]:
cars.Year[cars.Year>2018]

3       2019
12      2019
13      2019
16      2019
18      2020
        ...
2022    2021
2030    2021
2032    2020
2044    2022
2051    2021
Name: Year, Length: 587, dtype: int64

In [14]:
cars.Price[cars.Year>2018]

3        799000
12      1075000
13      1695000
16       449000
18       699000
         ...
2022    1975000
2030    1325000
2032    8900000
2044    2765000
2051     925000
Name: Price, Length: 587, dtype: int64

In [15]:
cars[cars.Year>2018]

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
12,Maruti Suzuki,Ciaz Alpha Hybrid 1.5 AT [2018-2020],1075000,2019,30672,Petrol,Automatic,Bangalore,Blue,First,Individual,1462 cc,103 bhp @ 6000 rpm,138 Nm @ 4400 rpm,FWD,4490.0,1730.0,1485.0,5.0,43.0
13,Tata,Harrier XZ [2019-2020],1695000,2019,20856,Diesel,Manual,Bangalore,Orange,First,Individual,1956 cc,138 bhp @ 3750 rpm,350 Nm @ 1750 rpm,FWD,4598.0,1894.0,1706.0,5.0,50.0
16,Maruti Suzuki,Alto 800 LXi (O),449000,2019,3583,Petrol,Manual,Bangalore,Grey,First,Individual,796 cc,47 bhp @ 6000 rpm,69 Nm @ 3500 rpm,FWD,3445.0,1515.0,1475.0,5.0,35.0
18,Maruti Suzuki,Wagon R ZXi 1.2 AMT,699000,2020,30777,Petrol,Automatic,Bangalore,White,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3655.0,1620.0,1675.0,5.0,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022,Kia,Seltos GTX Plus AT 1.4 [2019-2020],1975000,2021,7000,Petrol,Automatic,Bangalore,Grey,First,Individual,1353 cc,138 bhp @ 6000 rpm,242 Nm @ 1500 rpm,FWD,4315.0,1800.0,1645.0,5.0,50.0
2030,Kia,Sonet GTX Plus 1.0 iMT [2020-2021],1325000,2021,20000,Petrol,Manual,Bangalore,Maroon,First,Individual,998 cc,118 bhp @ 6000 rpm,172 Nm @ 1500 rpm,FWD,3995.0,1790.0,1647.0,5.0,45.0
2032,Land Rover,Range Rover Velar 2.0 S Petrol 250,8900000,2020,88000,Petrol,Automatic,Mumbai,White,First,Individual,1997 cc,247 bhp @ 5500 rpm,365 Nm @ 1500 rpm,AWD,4797.0,2032.0,1665.0,5.0,NaN
2044,Mahindra,XUV700 AX 7 Petrol AT Luxury Pack 7 STR,2765000,2022,75,Petrol,Automatic,Delhi,Blue,First,Individual,1997 cc,197 bhp @ 5000 rpm,380 Nm @ 1750 rpm,FWD,4695.0,1890.0,1755.0,7.0,60.0
2051,Maruti Suzuki,Vitara Brezza VXi,925000,2021,48000,Petrol,Manual,Bangalore,White,First,Individual,1462 cc,103 bhp @ 6000 rpm,138 Nm @ 4400 rpm,FWD,3995.0,1790.0,1640.0,5.0,48.0

In [18]:
cars[cars.Year>2018][["Model","Make"]]

                                        Model           Make
3                                    Glanza G         Toyota
12       Ciaz Alpha Hybrid 1.5 AT [2018-2020]  Maruti Suzuki
13                     Harrier XZ [2019-2020]           Tata
16                           Alto 800 LXi (O)  Maruti Suzuki
18                        Wagon R ZXi 1.2 AMT  Maruti Suzuki
...                                       ...            ...
2022       Seltos GTX Plus AT 1.4 [2019-2020]            Kia
2030       Sonet GTX Plus 1.0 iMT [2020-2021]            Kia
2032       Range Rover Velar 2.0 S Petrol 250     Land Rover
2044  XUV700 AX 7 Petrol AT Luxury Pack 7 STR       Mahindra
2051                        Vitara Brezza VXi  Maruti Suzuki

[587 rows x 2 columns]

In [19]:
cars[cars.Price>10e6]

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
95,Porsche,Cayenne Coupe Platinum Edition,16200000,2022,2766,Petrol,Automatic,Mumbai,Blue,First,Individual,2995 cc,335 bhp @ 5300 rpm,450 Nm @ 1340 rpm,AWD,4931.0,1983.0,1676.0,4.0,75.0
160,Mercedes-Benz,S-Class Maybach S 500,11500000,2016,27000,Petrol,Automatic,Delhi,Blue,First,Individual,4663 cc,453 bhp @ 5250 rpm,700 Nm @ 1800 rpm,RWD,5453.0,1899.0,1498.0,4.0,70.0
259,Land Rover,Range Rover Sport SE 2.0 Petrol,12500000,2022,22010,Petrol,Automatic,Mohali,White,First,Individual,1997 cc,296 bhp @ 5500 rpm,400 Nm @ 1500 rpm,AWD,4879.0,2073.0,1803.0,5.0,104.0
442,Mercedes-Benz,S-Class Maybach S 560,18500000,2021,21000,Petrol,Automatic,Gurgaon,Black,First,Individual,3982 cc,463 bhp @ 5250 rpm,700 Nm @ 2000 rpm,RWD,5462.0,1899.0,1498.0,4.0,70.0
483,Ferrari,488 GTB,35000000,2018,9500,Petrol,Automatic,Delhi,Black,First,Individual,3902 cc,660 bhp @ 8000 rpm,760 Nm @ 3000 rpm,RWD,4568.0,1952.0,1213.0,2.0,78.0
510,Lamborghini,Huracan LP 610-4,24000000,2016,6000,Petrol,Automatic,Delhi,Blue,First,Individual,5204 cc,602 bhp @ 8250 rpm,560 Nm @ 6500 rpm,AWD,4459.0,1924.0,1165.0,2.0,NaN
542,Mercedes-Benz,GLS 400d 4MATIC,13000000,2021,20000,Diesel,Automatic,Delhi,Blue,First,Individual,2925 cc,326 bhp @ 3600 rpm,700 Nm @ 1200 rpm,AWD,5207.0,2157.0,1823.0,7.0,90.0
582,Land Rover,Range Rover 3.0 V6 Diesel Vogue,22000000,2019,35000,Diesel,Automatic,Pune,Blue,First,Individual,2993 cc,244 bhp @ 4000 rpm,600 Nm @ 2000 rpm,AWD,4999.0,2220.0,1835.0,5.0,105.0
977,Rolls-Royce,Ghost 6.5,18000000,2011,60000,Petrol,Automatic,Mumbai,Maroon,Second,Corporate,6592 cc,570 bhp @ 5250 rpm,780 Nm @ 1500 rpm,RWD,5399.0,1948.0,1550.0,5.0,82.5
1154,Toyota,Vellfire Hybrid,11500000,2022,4000,Hybrid,Automatic,Delhi,Black,First,Individual,2494 cc,115 bhp @ 4700 rpm,198 Nm @ 2800 rpm,AWD,4935.0,1850.0,1895.0,7.0,58.0
1178,BMW,X6 xDrive40i M Sport,10800000,2021,20000,Petrol,Automatic,Chandigarh,Red,First,Individual,2998 cc,335 bhp @ 5500 rpm,450 Nm @ 1500 rpm,AWD,4935.0,2004.0,1696.0,5.0,83.0
1246,Rolls-Royce,Ghost Extended Wheelbase,20000000,2011,27000,Petrol,Automatic,Delhi,Blue,Third,Individual,6592 cc,570 bhp @ 5250 rpm,780 Nm @ 1500 rpm,RWD,5569.0,1948.0,1550.0,5.0,82.5
1275,Porsche,718 Boxster,10900000,2018,6300,Petrol,Automatic,Hyderabad,Grey,First,Corporate,1988 cc,295 bhp @ 6500 rpm,380 Nm @ 2150 rpm,RWD,4379.0,1801.0,1281.0,2.0,54.0
1305,Land Rover,Range Rover 3.0 V6 Diesel Vogue LWB,27500000,2020,11000,Diesel,Automatic,Hyderabad,White,Second,Individual,2993 cc,244 bhp @ 4000 rpm,600 Nm @ 2000 rpm,AWD,5199.0,2220.0,1840.0,4.0,105.0
1313,Land Rover,Range Rover 3.0 V6 Diesel Vogue,19300000,2019,63000,Diesel,Automatic,Bangalore,Black,First,Individual,2993 cc,244 bhp @ 4000 rpm,600 Nm @ 2000 rpm,AWD,4999.0,2220.0,1835.0,5.0,105.0
1369,Rolls-Royce,Ghost Extended Wheelbase,20000000,2012,55000,Petrol,Automatic,Chennai,White,Third,Individual,6592 cc,570 bhp @ 5250 rpm,780 Nm @ 1500 rpm,RWD,5569.0,1948.0,1550.0,5.0,82.5
1370,Mercedes-Benz,GLS 400d 4MATIC,12900000,2021,3000,Diesel,Automatic,Delhi,White,First,Individual,2925 cc,326 bhp @ 3600 rpm,700 Nm @ 1200 rpm,AWD,5207.0,2157.0,1823.0,7.0,90.0
1576,Mercedes-Benz,GLS 450 4MATIC,13100000,2021,17000,Petrol,Automatic,Delhi,White,First,Individual,2999 cc,362 bhp @ 5500 rpm,500 Nm @ 1600 rpm,AWD,5207.0,2157.0,1823.0,7.0,90.0
1742,BMW,X7 xDrive40i M Sport,12500000,2021,9500,Petrol,Automatic,Chandigarh,White,First,Individual,2998 cc,335 bhp @ 5500 rpm,450 Nm @ 1500 rpm,AWD,5151.0,2000.0,1805.0,6.0,83.0
1803,Porsche,Cayenne Base,14900000,2021,7534,Petrol,Automatic,Mumbai,Blue,UnRegistered Car,Individual,2995 cc,335 bhp @ 5300 rpm,450 Nm @ 1340 rpm,AWD,4918.0,1983.0,1696.0,5.0,75.0
1890,Mercedes-Benz,S-Class S 450,20000000,2021,6600,Petrol,Automatic,Delhi,White,First,Individual,2996 cc,362 bhp @ 5250 rpm,500 Nm @ 1800 rpm,RWD,5246.0,1899.0,1494.0,5.0,80.0
1912,Mercedes-Benz,S-Class S 350D [2018-2020],18500000,2021,5000,Diesel,Automatic,Pune,White,UnRegistered Car,Individual,2925 cc,282 bhp @ 3600 rpm,600 Nm @ 1600 rpm,RWD,5246.0,1899.0,1494.0,5.0,70.0

In [22]:
(cars.Price>100e6) & (cars.Year>2021)

0       False
1       False
2       False
3       False
4       False
        ...
2054    False
2055    False
2056    False
2057    False
2058    False
Length: 2059, dtype: bool

In [28]:
cars[(cars.Price>10e6) & (cars.Year>2021)]

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
95,Porsche,Cayenne Coupe Platinum Edition,16200000,2022,2766,Petrol,Automatic,Mumbai,Blue,First,Individual,2995 cc,335 bhp @ 5300 rpm,450 Nm @ 1340 rpm,AWD,4931.0,1983.0,1676.0,4.0,75.0
259,Land Rover,Range Rover Sport SE 2.0 Petrol,12500000,2022,22010,Petrol,Automatic,Mohali,White,First,Individual,1997 cc,296 bhp @ 5500 rpm,400 Nm @ 1500 rpm,AWD,4879.0,2073.0,1803.0,5.0,104.0
1154,Toyota,Vellfire Hybrid,11500000,2022,4000,Hybrid,Automatic,Delhi,Black,First,Individual,2494 cc,115 bhp @ 4700 rpm,198 Nm @ 2800 rpm,AWD,4935.0,1850.0,1895.0,7.0,58.0

In [33]:
cars.query("Price>10e6 and Year>2021")

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
95,Porsche,Cayenne Coupe Platinum Edition,16200000,2022,2766,Petrol,Automatic,Mumbai,Blue,First,Individual,2995 cc,335 bhp @ 5300 rpm,450 Nm @ 1340 rpm,AWD,4931.0,1983.0,1676.0,4.0,75.0
259,Land Rover,Range Rover Sport SE 2.0 Petrol,12500000,2022,22010,Petrol,Automatic,Mohali,White,First,Individual,1997 cc,296 bhp @ 5500 rpm,400 Nm @ 1500 rpm,AWD,4879.0,2073.0,1803.0,5.0,104.0
1154,Toyota,Vellfire Hybrid,11500000,2022,4000,Hybrid,Automatic,Delhi,Black,First,Individual,2494 cc,115 bhp @ 4700 rpm,198 Nm @ 2800 rpm,AWD,4935.0,1850.0,1895.0,7.0,58.0

In [34]:
cars.head()

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0

In [35]:
cars.Price

0        505000
1        450000
2        220000
3        799000
4       1950000
         ...
2054     850000
2055     275000
2056     240000
2057    4290000
2058     670000
Name: Price, Length: 2059, dtype: int64

In [36]:
cars["Price"]

0        505000
1        450000
2        220000
3        799000
4       1950000
         ...
2054     850000
2055     275000
2056     240000
2057    4290000
2058     670000
Name: Price, Length: 2059, dtype: int64

In [37]:
cars["Fuel Type"]

0       Petrol
1       Diesel
2       Petrol
3       Petrol
4       Diesel
         ...
2054    Diesel
2055    Petrol
2056    Petrol
2057    Diesel
2058    Diesel
Name: Fuel Type, Length: 2059, dtype: object

In [38]:
cars.Price

0        505000
1        450000
2        220000
3        799000
4       1950000
         ...
2054     850000
2055     275000
2056     240000
2057    4290000
2058     670000
Name: Price, Length: 2059, dtype: int64

In [39]:
cars.Price.sort_values()

491        49000
487        71001
824       100000
459       114999
1037      120000
          ...
1890    20000000
582     22000000
510     24000000
1305    27500000
483     35000000
Name: Price, Length: 2059, dtype: int64

In [40]:
cars.Price.sort_values(ascending=False)

483     35000000
1305    27500000
510     24000000
582     22000000
1369    20000000
          ...
1037      120000
459       114999
824       100000
487        71001
491        49000
Name: Price, Length: 2059, dtype: int64

In [41]:
cars.sort_values(["Price"])

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
491,Tata,Nano Base,49000,2010,60000,Petrol,Manual,Gurgaon,White,First,Individual,624 cc,35@5250,48@3000,RWD,3099.0,1495.0,1652.0,4.0,15.0
487,Maruti Suzuki,Zen LXi BS-II,71001,2004,65082,Petrol,Manual,Kolkata,Yellow,First,Individual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
824,Honda,City 1.5 EXi,100000,2002,65494,Petrol,Manual,Ranchi,Beige,First,Individual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
459,Tata,Manza Aqua Safire BS-IV,114999,2012,93000,Petrol,Manual,Unnao,Silver,Second,Individual,1368 cc,90@6000,116@4750,NaN,4413.0,1703.0,1550.0,5.0,44.0
1037,Maruti Suzuki,Ritz Vdi BS-IV,120000,2009,80000,Diesel,Manual,Kanpur,Silver,4 or More,Individual,1248 cc,75@4000,190@2000,NaN,3715.0,1680.0,1620.0,5.0,43.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1890,Mercedes-Benz,S-Class S 450,20000000,2021,6600,Petrol,Automatic,Delhi,White,First,Individual,2996 cc,362 bhp @ 5250 rpm,500 Nm @ 1800 rpm,RWD,5246.0,1899.0,1494.0,5.0,80.0
582,Land Rover,Range Rover 3.0 V6 Diesel Vogue,22000000,2019,35000,Diesel,Automatic,Pune,Blue,First,Individual,2993 cc,244 bhp @ 4000 rpm,600 Nm @ 2000 rpm,AWD,4999.0,2220.0,1835.0,5.0,105.0
510,Lamborghini,Huracan LP 610-4,24000000,2016,6000,Petrol,Automatic,Delhi,Blue,First,Individual,5204 cc,602 bhp @ 8250 rpm,560 Nm @ 6500 rpm,AWD,4459.0,1924.0,1165.0,2.0,NaN
1305,Land Rover,Range Rover 3.0 V6 Diesel Vogue LWB,27500000,2020,11000,Diesel,Automatic,Hyderabad,White,Second,Individual,2993 cc,244 bhp @ 4000 rpm,600 Nm @ 2000 rpm,AWD,5199.0,2220.0,1840.0,4.0,105.0
483,Ferrari,488 GTB,35000000,2018,9500,Petrol,Automatic,Delhi,Black,First,Individual,3902 cc,660 bhp @ 8000 rpm,760 Nm @ 3000 rpm,RWD,4568.0,1952.0,1213.0,2.0,78.0

In [42]:
cars.sort_values(["Price"],ascending=False)

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
483,Ferrari,488 GTB,35000000,2018,9500,Petrol,Automatic,Delhi,Black,First,Individual,3902 cc,660 bhp @ 8000 rpm,760 Nm @ 3000 rpm,RWD,4568.0,1952.0,1213.0,2.0,78.0
1305,Land Rover,Range Rover 3.0 V6 Diesel Vogue LWB,27500000,2020,11000,Diesel,Automatic,Hyderabad,White,Second,Individual,2993 cc,244 bhp @ 4000 rpm,600 Nm @ 2000 rpm,AWD,5199.0,2220.0,1840.0,4.0,105.0
510,Lamborghini,Huracan LP 610-4,24000000,2016,6000,Petrol,Automatic,Delhi,Blue,First,Individual,5204 cc,602 bhp @ 8250 rpm,560 Nm @ 6500 rpm,AWD,4459.0,1924.0,1165.0,2.0,NaN
582,Land Rover,Range Rover 3.0 V6 Diesel Vogue,22000000,2019,35000,Diesel,Automatic,Pune,Blue,First,Individual,2993 cc,244 bhp @ 4000 rpm,600 Nm @ 2000 rpm,AWD,4999.0,2220.0,1835.0,5.0,105.0
1369,Rolls-Royce,Ghost Extended Wheelbase,20000000,2012,55000,Petrol,Automatic,Chennai,White,Third,Individual,6592 cc,570 bhp @ 5250 rpm,780 Nm @ 1500 rpm,RWD,5569.0,1948.0,1550.0,5.0,82.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1037,Maruti Suzuki,Ritz Vdi BS-IV,120000,2009,80000,Diesel,Manual,Kanpur,Silver,4 or More,Individual,1248 cc,75@4000,190@2000,NaN,3715.0,1680.0,1620.0,5.0,43.0
459,Tata,Manza Aqua Safire BS-IV,114999,2012,93000,Petrol,Manual,Unnao,Silver,Second,Individual,1368 cc,90@6000,116@4750,NaN,4413.0,1703.0,1550.0,5.0,44.0
824,Honda,City 1.5 EXi,100000,2002,65494,Petrol,Manual,Ranchi,Beige,First,Individual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487,Maruti Suzuki,Zen LXi BS-II,71001,2004,65082,Petrol,Manual,Kolkata,Yellow,First,Individual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
491,Tata,Nano Base,49000,2010,60000,Petrol,Manual,Gurgaon,White,First,Individual,624 cc,35@5250,48@3000,RWD,3099.0,1495.0,1652.0,4.0,15.0

In [43]:
cars.sort_values(["Price"],ascending=False).head(10)

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
483,Ferrari,488 GTB,35000000,2018,9500,Petrol,Automatic,Delhi,Black,First,Individual,3902 cc,660 bhp @ 8000 rpm,760 Nm @ 3000 rpm,RWD,4568.0,1952.0,1213.0,2.0,78.0
1305,Land Rover,Range Rover 3.0 V6 Diesel Vogue LWB,27500000,2020,11000,Diesel,Automatic,Hyderabad,White,Second,Individual,2993 cc,244 bhp @ 4000 rpm,600 Nm @ 2000 rpm,AWD,5199.0,2220.0,1840.0,4.0,105.0
510,Lamborghini,Huracan LP 610-4,24000000,2016,6000,Petrol,Automatic,Delhi,Blue,First,Individual,5204 cc,602 bhp @ 8250 rpm,560 Nm @ 6500 rpm,AWD,4459.0,1924.0,1165.0,2.0,NaN
582,Land Rover,Range Rover 3.0 V6 Diesel Vogue,22000000,2019,35000,Diesel,Automatic,Pune,Blue,First,Individual,2993 cc,244 bhp @ 4000 rpm,600 Nm @ 2000 rpm,AWD,4999.0,2220.0,1835.0,5.0,105.0
1369,Rolls-Royce,Ghost Extended Wheelbase,20000000,2012,55000,Petrol,Automatic,Chennai,White,Third,Individual,6592 cc,570 bhp @ 5250 rpm,780 Nm @ 1500 rpm,RWD,5569.0,1948.0,1550.0,5.0,82.5
1246,Rolls-Royce,Ghost Extended Wheelbase,20000000,2011,27000,Petrol,Automatic,Delhi,Blue,Third,Individual,6592 cc,570 bhp @ 5250 rpm,780 Nm @ 1500 rpm,RWD,5569.0,1948.0,1550.0,5.0,82.5
1890,Mercedes-Benz,S-Class S 450,20000000,2021,6600,Petrol,Automatic,Delhi,White,First,Individual,2996 cc,362 bhp @ 5250 rpm,500 Nm @ 1800 rpm,RWD,5246.0,1899.0,1494.0,5.0,80.0
1313,Land Rover,Range Rover 3.0 V6 Diesel Vogue,19300000,2019,63000,Diesel,Automatic,Bangalore,Black,First,Individual,2993 cc,244 bhp @ 4000 rpm,600 Nm @ 2000 rpm,AWD,4999.0,2220.0,1835.0,5.0,105.0
1912,Mercedes-Benz,S-Class S 350D [2018-2020],18500000,2021,5000,Diesel,Automatic,Pune,White,UnRegistered Car,Individual,2925 cc,282 bhp @ 3600 rpm,600 Nm @ 1600 rpm,RWD,5246.0,1899.0,1494.0,5.0,70.0
442,Mercedes-Benz,S-Class Maybach S 560,18500000,2021,21000,Petrol,Automatic,Gurgaon,Black,First,Individual,3982 cc,463 bhp @ 5250 rpm,700 Nm @ 2000 rpm,RWD,5462.0,1899.0,1498.0,4.0,70.0

In [44]:
cars.head()

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0

In [46]:
cars[cars.Make=="Toyota"]

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0
37,Toyota,Innova 2.4 G 8 STR [2016-2017],1900000,2019,71000,Diesel,Manual,Mumbai,Bronze,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,8.0,55.0
41,Toyota,Corolla Altis VL AT Petrol,1095000,2016,45000,Petrol,Automatic,Mumbai,Black,First,Individual,1798 cc,138 bhp @ 6400 rpm,173 Nm @ 4000 rpm,FWD,4620.0,1775.0,1475.0,5.0,55.0
55,Toyota,Innova 2.5 GX BS IV 7 STR,865000,2015,43634,Diesel,Manual,Delhi,Silver,First,Individual,2494 cc,101 bhp @ 3600 rpm,200 Nm @ 1200 rpm,RWD,4585.0,1765.0,1760.0,7.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1992,Toyota,Innova 2.0 G1 BS-IV,555000,2010,261236,Petrol,Manual,Mumbai,Silver,First,Individual,1998 cc,136@5600,182@4000,NaN,4555.0,1770.0,1755.0,8.0,55.0
2021,Toyota,Fortuner 2.8 4x2 MT [2016-2020],3250000,2018,173000,Diesel,Manual,Bangalore,White,First,Individual,2755 cc,174 bhp @ 3400 rpm,420 Nm @ 1600 rpm,RWD,4795.0,1855.0,1835.0,7.0,80.0
2026,Toyota,Etios Liva G,315000,2011,38091,Petrol,Manual,Mumbai,Red,First,Individual,1197 cc,80 bhp @ 5600 rpm,104 Nm @ 3100 rpm,FWD,3775.0,1695.0,1510.0,5.0,45.0
2029,Toyota,Etios VXD,465000,2014,82000,Diesel,Manual,Ludhiana,Silver,First,Individual,1364 cc,67 bhp @ 3800 rpm,170 Nm @ 1800 rpm,FWD,4265.0,1695.0,1510.0,5.0,45.0
2036,Toyota,Fortuner 3.0 MT,1000000,2010,127000,Diesel,Manual,Guwahati,White,Third,Individual,2982 cc,171@3600,343@1400,AWD,4695.0,1840.0,1850.0,7.0,80.0

In [47]:
cars.set_index(["Make"])

,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
Make,,,,,,,,,,,,,,,,,,,
Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mahindra,XUV500 W8 [2015-2017],850000,2016,90300,Diesel,Manual,Surat,White,First,Individual,2179 cc,138 bhp @ 3750 rpm,330 Nm @ 1600 rpm,FWD,4585.0,1890.0,1785.0,7.0,70.0
Hyundai,Eon D-Lite +,275000,2014,83000,Petrol,Manual,Ahmedabad,White,Second,Individual,814 cc,55 bhp @ 5500 rpm,75 Nm @ 4000 rpm,FWD,3495.0,1550.0,1500.0,5.0,32.0
Ford,Figo Duratec Petrol ZXI 1.2,240000,2013,73000,Petrol,Manual,Thane,Silver,First,Individual,1196 cc,70 bhp @ 6250 rpm,102 Nm @ 4000 rpm,FWD,3795.0,1680.0,1427.0,5.0,45.0
BMW,5-Series 520d Luxury Line [2017-2019],4290000,2018,60474,Diesel,Automatic,Coimbatore,White,First,Individual,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,RWD,4936.0,1868.0,1479.0,5.0,65.0
Mahindra,Bolero Power Plus ZLX [2016-2019],670000,2017,72000,Diesel,Manual,Guwahati,White,First,Individual,1493 cc,70 bhp @ 3600 rpm,195 Nm @ 1400 rpm,RWD,3995.0,1745.0,1880.0,7.0,NaN

In [48]:
cars1=cars.set_index(["Make"])

In [52]:
cars1.loc["Toyota"]

,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
Make,,,,,,,,,,,,,,,,,,,
Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0
Toyota,Innova 2.4 G 8 STR [2016-2017],1900000,2019,71000,Diesel,Manual,Mumbai,Bronze,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,8.0,55.0
Toyota,Corolla Altis VL AT Petrol,1095000,2016,45000,Petrol,Automatic,Mumbai,Black,First,Individual,1798 cc,138 bhp @ 6400 rpm,173 Nm @ 4000 rpm,FWD,4620.0,1775.0,1475.0,5.0,55.0
Toyota,Innova 2.5 GX BS IV 7 STR,865000,2015,43634,Diesel,Manual,Delhi,Silver,First,Individual,2494 cc,101 bhp @ 3600 rpm,200 Nm @ 1200 rpm,RWD,4585.0,1765.0,1760.0,7.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Toyota,Innova 2.0 G1 BS-IV,555000,2010,261236,Petrol,Manual,Mumbai,Silver,First,Individual,1998 cc,136@5600,182@4000,NaN,4555.0,1770.0,1755.0,8.0,55.0
Toyota,Fortuner 2.8 4x2 MT [2016-2020],3250000,2018,173000,Diesel,Manual,Bangalore,White,First,Individual,2755 cc,174 bhp @ 3400 rpm,420 Nm @ 1600 rpm,RWD,4795.0,1855.0,1835.0,7.0,80.0
Toyota,Etios Liva G,315000,2011,38091,Petrol,Manual,Mumbai,Red,First,Individual,1197 cc,80 bhp @ 5600 rpm,104 Nm @ 3100 rpm,FWD,3775.0,1695.0,1510.0,5.0,45.0
Toyota,Etios VXD,465000,2014,82000,Diesel,Manual,Ludhiana,Silver,First,Individual,1364 cc,67 bhp @ 3800 rpm,170 Nm @ 1800 rpm,FWD,4265.0,1695.0,1510.0,5.0,45.0
Toyota,Fortuner 3.0 MT,1000000,2010,127000,Diesel,Manual,Guwahati,White,Third,Individual,2982 cc,171@3600,343@1400,AWD,4695.0,1840.0,1850.0,7.0,80.0

In [53]:
cars

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,Mahindra,XUV500 W8 [2015-2017],850000,2016,90300,Diesel,Manual,Surat,White,First,Individual,2179 cc,138 bhp @ 3750 rpm,330 Nm @ 1600 rpm,FWD,4585.0,1890.0,1785.0,7.0,70.0
2055,Hyundai,Eon D-Lite +,275000,2014,83000,Petrol,Manual,Ahmedabad,White,Second,Individual,814 cc,55 bhp @ 5500 rpm,75 Nm @ 4000 rpm,FWD,3495.0,1550.0,1500.0,5.0,32.0
2056,Ford,Figo Duratec Petrol ZXI 1.2,240000,2013,73000,Petrol,Manual,Thane,Silver,First,Individual,1196 cc,70 bhp @ 6250 rpm,102 Nm @ 4000 rpm,FWD,3795.0,1680.0,1427.0,5.0,45.0
2057,BMW,5-Series 520d Luxury Line [2017-2019],4290000,2018,60474,Diesel,Automatic,Coimbatore,White,First,Individual,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,RWD,4936.0,1868.0,1479.0,5.0,65.0
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],670000,2017,72000,Diesel,Manual,Guwahati,White,First,Individual,1493 cc,70 bhp @ 3600 rpm,195 Nm @ 1400 rpm,RWD,3995.0,1745.0,1880.0,7.0,NaN

In [54]:
cars.set_index(["Make"])

,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
Make,,,,,,,,,,,,,,,,,,,
Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mahindra,XUV500 W8 [2015-2017],850000,2016,90300,Diesel,Manual,Surat,White,First,Individual,2179 cc,138 bhp @ 3750 rpm,330 Nm @ 1600 rpm,FWD,4585.0,1890.0,1785.0,7.0,70.0
Hyundai,Eon D-Lite +,275000,2014,83000,Petrol,Manual,Ahmedabad,White,Second,Individual,814 cc,55 bhp @ 5500 rpm,75 Nm @ 4000 rpm,FWD,3495.0,1550.0,1500.0,5.0,32.0
Ford,Figo Duratec Petrol ZXI 1.2,240000,2013,73000,Petrol,Manual,Thane,Silver,First,Individual,1196 cc,70 bhp @ 6250 rpm,102 Nm @ 4000 rpm,FWD,3795.0,1680.0,1427.0,5.0,45.0
BMW,5-Series 520d Luxury Line [2017-2019],4290000,2018,60474,Diesel,Automatic,Coimbatore,White,First,Individual,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,RWD,4936.0,1868.0,1479.0,5.0,65.0
Mahindra,Bolero Power Plus ZLX [2016-2019],670000,2017,72000,Diesel,Manual,Guwahati,White,First,Individual,1493 cc,70 bhp @ 3600 rpm,195 Nm @ 1400 rpm,RWD,3995.0,1745.0,1880.0,7.0,NaN

In [55]:
cars.set_index(["Make","Model"])

                                                       Price  Year  Kilometer  \
Make          Model
Honda         Amaze 1.2 VX i-VTEC                     505000  2017      87150
Maruti Suzuki Swift DZire VDI                         450000  2014      75000
Hyundai       i10 Magna 1.2 Kappa2                    220000  2011      67000
Toyota        Glanza G                                799000  2019      37500
              Innova 2.4 VX 7 STR [2016-2020]        1950000  2018      69000
...                                                      ...   ...        ...
Mahindra      XUV500 W8 [2015-2017]                   850000  2016      90300
Hyundai       Eon D-Lite +                            275000  2014      83000
Ford          Figo Duratec Petrol ZXI 1.2             240000  2013      73000
BMW           5-Series 520d Luxury Line [2017-2019]  4290000  2018      60474
Mahindra      Bolero Power Plus ZLX [2016-2019]       670000  2017      72000

                                                    Fuel Type Transmission  \
Make          Model
Honda         Amaze 1.2 VX i-VTEC                      Petrol       Manual
Maruti Suzuki Swift DZire VDI                          Diesel       Manual
Hyundai       i10 Magna 1.2 Kappa2                     Petrol       Manual
Toyota        Glanza G                                 Petrol       Manual
              Innova 2.4 VX 7 STR [2016-2020]          Diesel       Manual
...                                                       ...          ...
Mahindra      XUV500 W8 [2015-2017]                    Diesel       Manual
Hyundai       Eon D-Lite +                             Petrol       Manual
Ford          Figo Duratec Petrol ZXI 1.2              Petrol       Manual
BMW           5-Series 520d Luxury Line [2017-2019]    Diesel    Automatic
Mahindra      Bolero Power Plus ZLX [2016-2019]        Diesel       Manual

                                                       Location   Color  \
Make          Model
Honda         Amaze 1.2 VX i-VTEC                          Pune    Grey
Maruti Suzuki Swift DZire VDI                          Ludhiana   White
Hyundai       i10 Magna 1.2 Kappa2                      Lucknow  Maroon
Toyota        Glanza G                                Mangalore     Red
              Innova 2.4 VX 7 STR [2016-2020]            Mumbai    Grey
...                                                         ...     ...
Mahindra      XUV500 W8 [2015-2017]                       Surat   White
Hyundai       Eon D-Lite +                            Ahmedabad   White
Ford          Figo Duratec Petrol ZXI 1.2                 Thane  Silver
BMW           5-Series 520d Luxury Line [2017-2019]  Coimbatore   White
Mahindra      Bolero Power Plus ZLX [2016-2019]        Guwahati   White

                                                      Owner Seller Type  \
Make          Model
Honda         Amaze 1.2 VX i-VTEC                     First   Corporate
Maruti Suzuki Swift DZire VDI                        Second  Individual
Hyundai       i10 Magna 1.2 Kappa2                    First  Individual
Toyota        Glanza G                                First  Individual
              Innova 2.4 VX 7 STR [2016-2020]         First  Individual
...                                                     ...         ...
Mahindra      XUV500 W8 [2015-2017]                   First  Individual
Hyundai       Eon D-Lite +                           Second  Individual
Ford          Figo Duratec Petrol ZXI 1.2             First  Individual
BMW           5-Series 520d Luxury Line [2017-2019]   First  Individual
Mahindra      Bolero Power Plus ZLX [2016-2019]       First  Individual

                                                      Engine  \
Make          Model
Honda         Amaze 1.2 VX i-VTEC                    1198 cc
Maruti Suzuki Swift DZire VDI                        1248 cc
Hyundai       i10 Magna 1.2 Kappa2                   1197 cc
Toyota        Glanza G                               1197 cc
              Innova 2.4 VX 7 STR [2016-2020]        2393 cc
...                                                      ...
Mahindra      XUV500 W8 [2015-2017]                  2179 cc
Hyundai       Eon D-Lite +                            814 cc
Ford          Figo Duratec Petrol ZXI 1.2            1196 cc
BMW           5-Series 520d Luxury Line [2017-2019]  1995 cc
Mahindra      Bolero Power Plus ZLX [2016-2019]      1493 cc

                                                              Max Power  \
Make          Model
Honda         Amaze 1.2 VX i-VTEC                     87 bhp @ 6000 rpm
Maruti Suzuki Swift DZire VDI                         74 bhp @ 4000 rpm
Hyundai       i10 Magna 1.2 Kappa2                    79 bhp @ 6000 rpm
Toyota        Glanza G                                82 bhp @ 6000 rpm
              Innova 2.4 VX 7 STR [2016-2020]        148 bhp @ 3400 rpm
...                                                                 ...
Mahindra      XUV500 W8 [2015-2017]                  138 bhp @ 3750 rpm
Hyundai       Eon D-Lite +                            55 bhp @ 5500 rpm
Ford          Figo Duratec Petrol ZXI 1.2             70 bhp @ 6250 rpm
BMW           5-Series 520d Luxury Line [2017-2019]  188 bhp @ 4000 rpm
Mahindra      Bolero Power Plus ZLX [2016-2019]       70 bhp @ 3600 rpm

                                                                 Max Torque  \
Make          Model
Honda         Amaze 1.2 VX i-VTEC                         109 Nm @ 4500 rpm
Maruti Suzuki Swift DZire VDI                             190 Nm @ 2000 rpm
Hyundai       i10 Magna 1.2 Kappa2                   112.7619 Nm @ 4000 rpm
Toyota        Glanza G                                    113 Nm @ 4200 rpm
              Innova 2.4 VX 7 STR [2016-2020]             343 Nm @ 1400 rpm
...                                                                     ...
Mahindra      XUV500 W8 [2015-2017]                       330 Nm @ 1600 rpm
Hyundai       Eon D-Lite +                                 75 Nm @ 4000 rpm
Ford          Figo Duratec Petrol ZXI 1.2                 102 Nm @ 4000 rpm
BMW           5-Series 520d Luxury Line [2017-2019]       400 Nm @ 1750 rpm
Mahindra      Bolero Power Plus ZLX [2016-2019]           195 Nm @ 1400 rpm

                                                    Drivetrain  Length  \
Make          Model
Honda         Amaze 1.2 VX i-VTEC                          FWD  3990.0
Maruti Suzuki Swift DZire VDI                              FWD  3995.0
Hyundai       i10 Magna 1.2 Kappa2                         FWD  3585.0
Toyota        Glanza G                                     FWD  3995.0
              Innova 2.4 VX 7 STR [2016-2020]              RWD  4735.0
...                                                        ...     ...
Mahindra      XUV500 W8 [2015-2017]                        FWD  4585.0
Hyundai       Eon D-Lite +                                 FWD  3495.0
Ford          Figo Duratec Petrol ZXI 1.2                  FWD  3795.0
BMW           5-Series 520d Luxury Line [2017-2019]        RWD  4936.0
Mahindra      Bolero Power Plus ZLX [2016-2019]            RWD  3995.0

                                                      Width  Height  \
Make          Model
Honda         Amaze 1.2 VX i-VTEC                    1680.0  1505.0
Maruti Suzuki Swift DZire VDI                        1695.0  1555.0
Hyundai       i10 Magna 1.2 Kappa2                   1595.0  1550.0
Toyota        Glanza G                               1745.0  1510.0
              Innova 2.4 VX 7 STR [2016-2020]        1830.0  1795.0
...                                                     ...     ...
Mahindra      XUV500 W8 [2015-2017]                  1890.0  1785.0
Hyundai       Eon D-Lite +                           1550.0  1500.0
Ford          Figo Duratec Petrol ZXI 1.2            1680.0  1427.0
BMW           5-Series 520d Luxury Line [2017-2019]  1868.0  1479.0
Mahindra      Bolero Power Plus ZLX [2016-2019]      1745.0  1880.0

                                                     Seating Capacity  \
Make          Model
Honda         Amaze 1.2 VX i-VTEC                                 5.0
Maruti Suzuki Swift DZire VDI                                     5.0
Hyundai       i10 Magna 1.2 Kappa2                                5.0
Toyota        Glanza G                                            5.0
              Innova 2.4 VX 7 STR [2016-2020]                     7.0
...                                                               ...
Mahindra      XUV500 W8 [2015-2017]                               7.0
Hyundai       Eon D-Lite +                                        5.0
Ford          Figo Duratec Petrol ZXI 1.2                         5.0
BMW           5-Series 520d Luxury Line [2017-2019]               5.0
Mahindra      Bolero Power Plus ZLX [2016-2019]                   7.0

                                                     Fuel Tank Capacity
Make          Model
Honda         Amaze 1.2 VX i-VTEC                                  35.0
Maruti Suzuki Swift DZire VDI                                      42.0
Hyundai       i10 Magna 1.2 Kappa2                                 35.0
Toyota        Glanza G                                             37.0
              Innova 2.4 VX 7 STR [2016-2020]                      55.0
...                                                                 ...
Mahindra      XUV500 W8 [2015-2017]                                70.0
Hyundai       Eon D-Lite +                                         32.0
Ford          Figo Duratec Petrol ZXI 1.2                          45.0
BMW           5-Series 520d Luxury Line [2017-2019]                65.0
Mahindra      Bolero Power Plus ZLX [2016-2019]                     NaN

[2059 rows x 18 columns]

In [57]:
cars.sort_values(["Make","Model"])#.set_index(["Make","Model"])

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
718,Audi,A3 35 TDI Premium,2600000,2017,64000,Diesel,Automatic,Chennai,Blue,First,Individual,1968 cc,141 bhp @ 3500 rpm,320 Nm @ 1750 rpm,FWD,4456.0,1796.0,1416.0,5.0,50.0
734,Audi,A3 35 TDI Premium,1800000,2014,76529,Diesel,Automatic,Pune,Blue,First,Individual,1968 cc,141 bhp @ 3500 rpm,320 Nm @ 1750 rpm,FWD,4456.0,1796.0,1416.0,5.0,50.0
910,Audi,A3 35 TDI Premium,2950000,2020,11000,Diesel,Automatic,Pune,White,First,Individual,1968 cc,141 bhp @ 3500 rpm,320 Nm @ 1750 rpm,FWD,4456.0,1796.0,1416.0,5.0,50.0
950,Audi,A3 35 TDI Premium,2900000,2019,15529,Diesel,Automatic,Mumbai,White,First,Individual,1968 cc,141 bhp @ 3500 rpm,320 Nm @ 1750 rpm,FWD,4456.0,1796.0,1416.0,5.0,50.0
605,Audi,A3 35 TDI Premium + Sunroof,2900000,2019,15530,Diesel,Automatic,Goa,White,First,Individual,1968 cc,141 bhp @ 3500 rpm,320 Nm @ 1750 rpm,FWD,4456.0,1796.0,1416.0,5.0,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1923,Volvo,XC40 D4 R-Design,3950000,2018,52000,Diesel,Automatic,Bangalore,White,First,Individual,1969 cc,190 bhp @ 4000 rpm,400 Nm @ 1750 rpm,AWD,4425.0,1863.0,1652.0,5.0,54.0
1597,Volvo,XC40 T4 R-Design,4400000,2020,16519,Petrol,Automatic,Mumbai,White,First,Corporate,1969 cc,187 bhp @ 5000 rpm,300 Nm @ 1300 rpm,FWD,4425.0,1863.0,1652.0,5.0,54.0
1775,Volvo,XC60 Inscription,1950000,2016,79000,Diesel,Automatic,Ahmedabad,White,First,Individual,2400 cc,215 bhp @ 4000 rpm,440 Nm @ 1500 rpm,AWD,4644.0,1891.0,1713.0,5.0,70.0
902,Volvo,XC60 Inscription [2017-2020],5800000,2019,3500,Diesel,Automatic,Ludhiana,White,First,Individual,1969 cc,235 bhp @ 4250 rpm,480 Nm @ 1750 rpm,AWD,4688.0,1902.0,1658.0,5.0,71.0
1778,Volvo,XC90 D5 Inscription,8500000,2021,32500,Diesel,Automatic,Ahmedabad,White,First,Individual,1969 cc,232 bhp @ 4250 rpm,480 Nm @ 1750 rpm,AWD,4953.0,2008.0,1776.0,7.0,71.0

In [59]:
sort_index=["Make","Model"]
cars.sort_values(sort_index).set_index(sort_index)

                                      Price  Year  Kilometer Fuel Type  \
Make  Model
Audi  A3 35 TDI Premium             2600000  2017      64000    Diesel
      A3 35 TDI Premium             1800000  2014      76529    Diesel
      A3 35 TDI Premium             2950000  2020      11000    Diesel
      A3 35 TDI Premium             2900000  2019      15529    Diesel
      A3 35 TDI Premium + Sunroof   2900000  2019      15530    Diesel
...                                     ...   ...        ...       ...
Volvo XC40 D4 R-Design              3950000  2018      52000    Diesel
      XC40 T4 R-Design              4400000  2020      16519    Petrol
      XC60 Inscription              1950000  2016      79000    Diesel
      XC60 Inscription [2017-2020]  5800000  2019       3500    Diesel
      XC90 D5 Inscription           8500000  2021      32500    Diesel

                                   Transmission   Location  Color  Owner  \
Make  Model
Audi  A3 35 TDI Premium               Automatic    Chennai   Blue  First
      A3 35 TDI Premium               Automatic       Pune   Blue  First
      A3 35 TDI Premium               Automatic       Pune  White  First
      A3 35 TDI Premium               Automatic     Mumbai  White  First
      A3 35 TDI Premium + Sunroof     Automatic        Goa  White  First
...                                         ...        ...    ...    ...
Volvo XC40 D4 R-Design                Automatic  Bangalore  White  First
      XC40 T4 R-Design                Automatic     Mumbai  White  First
      XC60 Inscription                Automatic  Ahmedabad  White  First
      XC60 Inscription [2017-2020]    Automatic   Ludhiana  White  First
      XC90 D5 Inscription             Automatic  Ahmedabad  White  First

                                   Seller Type   Engine           Max Power  \
Make  Model
Audi  A3 35 TDI Premium             Individual  1968 cc  141 bhp @ 3500 rpm
      A3 35 TDI Premium             Individual  1968 cc  141 bhp @ 3500 rpm
      A3 35 TDI Premium             Individual  1968 cc  141 bhp @ 3500 rpm
      A3 35 TDI Premium             Individual  1968 cc  141 bhp @ 3500 rpm
      A3 35 TDI Premium + Sunroof   Individual  1968 cc  141 bhp @ 3500 rpm
...                                        ...      ...                 ...
Volvo XC40 D4 R-Design              Individual  1969 cc  190 bhp @ 4000 rpm
      XC40 T4 R-Design               Corporate  1969 cc  187 bhp @ 5000 rpm
      XC60 Inscription              Individual  2400 cc  215 bhp @ 4000 rpm
      XC60 Inscription [2017-2020]  Individual  1969 cc  235 bhp @ 4250 rpm
      XC90 D5 Inscription           Individual  1969 cc  232 bhp @ 4250 rpm

                                           Max Torque Drivetrain  Length  \
Make  Model
Audi  A3 35 TDI Premium             320 Nm @ 1750 rpm        FWD  4456.0
      A3 35 TDI Premium             320 Nm @ 1750 rpm        FWD  4456.0
      A3 35 TDI Premium             320 Nm @ 1750 rpm        FWD  4456.0
      A3 35 TDI Premium             320 Nm @ 1750 rpm        FWD  4456.0
      A3 35 TDI Premium + Sunroof   320 Nm @ 1750 rpm        FWD  4456.0
...                                               ...        ...     ...
Volvo XC40 D4 R-Design              400 Nm @ 1750 rpm        AWD  4425.0
      XC40 T4 R-Design              300 Nm @ 1300 rpm        FWD  4425.0
      XC60 Inscription              440 Nm @ 1500 rpm        AWD  4644.0
      XC60 Inscription [2017-2020]  480 Nm @ 1750 rpm        AWD  4688.0
      XC90 D5 Inscription           480 Nm @ 1750 rpm        AWD  4953.0

                                     Width  Height  Seating Capacity  \
Make  Model
Audi  A3 35 TDI Premium             1796.0  1416.0               5.0
      A3 35 TDI Premium             1796.0  1416.0               5.0
      A3 35 TDI Premium             1796.0  1416.0               5.0
      A3 35 TDI Premium             1796.0  1416.0               5.0
      A3 35 TDI Premium + Sunroof   1796.0  1416.0               5.0
...                                    ...     ...               ...
Volvo XC40 D4 R-Design              1863.0  1652.0               5.0
      XC40 T4 R-Design              1863.0  1652.0               5.0
      XC60 Inscription              1891.0  1713.0               5.0
      XC60 Inscription [2017-2020]  1902.0  1658.0               5.0
      XC90 D5 Inscription           2008.0  1776.0               7.0

                                    Fuel Tank Capacity
Make  Model
Audi  A3 35 TDI Premium                           50.0
      A3 35 TDI Premium                           50.0
      A3 35 TDI Premium                           50.0
      A3 35 TDI Premium                           50.0
      A3 35 TDI Premium + Sunroof                 50.0
...                                                ...
Volvo XC40 D4 R-Design                            54.0
      XC40 T4 R-Design                            54.0
      XC60 Inscription                            70.0
      XC60 Inscription [2017-2020]                71.0
      XC90 D5 Inscription                         71.0

[2059 rows x 18 columns]