In [2]:
import pandas as pd
import numpy as np

In [5]:
table1=pd.DataFrame({"name":["Charles","Clayton","Esther","Okon","ChemChris"],
             "age":np.random.randint(20,60,5)})

In [9]:
table2=pd.DataFrame({"name":["Clayton","Esther","ChemChris"],
             "state":["Delta","Imo","Delta"]})

In [7]:
table1

        name  age
0    Charles   52
1    Clayton   27
2     Esther   40
3       Okon   27
4  ChemChris   45

In [10]:
table2

        name  state
0    Clayton  Delta
1     Esther    Imo
2  ChemChris  Delta

In [11]:
pd.merge(table1,table2)

        name  age  state
0    Clayton   27  Delta
1     Esther   40    Imo
2  ChemChris   45  Delta

In [13]:
pd.merge(table1,table2,how="inner")

        name  age  state
0    Clayton   27  Delta
1     Esther   40    Imo
2  ChemChris   45  Delta

In [15]:
pd.merge(table1,table2,how="inner", on="age")

KeyError: 'age'

In [21]:
table1["isMarried"]=pd.Series([True,True,False,False,True])
table2["isMarried"]=pd.Series([True,True,True])

In [18]:
table1

        name  age  isMarried
0    Charles   52       True
1    Clayton   27       True
2     Esther   40      False
3       Okon   27      False
4  ChemChris   45       True

In [22]:
table2

        name  state  isMarried
0    Clayton  Delta       True
1     Esther    Imo       True
2  ChemChris  Delta       True

In [23]:
pd.merge(table1,table2)

        name  age  isMarried  state
0    Clayton   27       True  Delta
1  ChemChris   45       True  Delta

In [24]:
pd.merge(table1,table2,on="name")

        name  age  isMarried_x  state  isMarried_y
0    Clayton   27         True  Delta         True
1     Esther   40        False    Imo         True
2  ChemChris   45         True  Delta         True

In [26]:
pd.merge(table1,table2,on="isMarried")

      name_x  age  isMarried     name_y  state
0    Charles   52       True    Clayton  Delta
1    Charles   52       True     Esther    Imo
2    Charles   52       True  ChemChris  Delta
3    Clayton   27       True    Clayton  Delta
4    Clayton   27       True     Esther    Imo
5    Clayton   27       True  ChemChris  Delta
6  ChemChris   45       True    Clayton  Delta
7  ChemChris   45       True     Esther    Imo
8  ChemChris   45       True  ChemChris  Delta

In [28]:
table1

        name  age  isMarried
0    Charles   52       True
1    Clayton   27       True
2     Esther   40      False
3       Okon   27      False
4  ChemChris   45       True

In [29]:
pd.merge(table1,table2,how="left",on="name")

        name  age  isMarried_x  state isMarried_y
0    Charles   52         True    NaN         NaN
1    Clayton   27         True  Delta        True
2     Esther   40        False    Imo        True
3       Okon   27        False    NaN         NaN
4  ChemChris   45         True  Delta        True

In [30]:
pd.merge(table2,table1,how="left",on="name")

        name  state  isMarried_x  age  isMarried_y
0    Clayton  Delta         True   27         True
1     Esther    Imo         True   40        False
2  ChemChris  Delta         True   45         True

In [31]:
pd.merge(table1,table2,how="right",on="name")

        name  age  isMarried_x  state  isMarried_y
0    Clayton   27         True  Delta         True
1     Esther   40        False    Imo         True
2  ChemChris   45         True  Delta         True

In [34]:
pd.merge(table2,table1,how="outer",on="name")

        name  state isMarried_x  age  isMarried_y
0    Clayton  Delta        True   27         True
1     Esther    Imo        True   40        False
2  ChemChris  Delta        True   45         True
3    Charles    NaN         NaN   52         True
4       Okon    NaN         NaN   27        False

In [36]:
pd.concat([table1,table2])

        name   age  isMarried  state
0    Charles  52.0       True    NaN
1    Clayton  27.0       True    NaN
2     Esther  40.0      False    NaN
3       Okon  27.0      False    NaN
4  ChemChris  45.0       True    NaN
0    Clayton   NaN       True  Delta
1     Esther   NaN       True    Imo
2  ChemChris   NaN       True  Delta

In [38]:
comb=pd.concat([table1,table2],axis=1)

In [39]:
comb

        name  age isMarried       name  state isMarried
0    Charles   52      True    Clayton  Delta      True
1    Clayton   27      True     Esther    Imo      True
2     Esther   40     False  ChemChris  Delta      True
3       Okon   27     False        NaN    NaN       NaN
4  ChemChris   45      True        NaN    NaN       NaN

In [40]:
comb["name"]

        name       name
0    Charles    Clayton
1    Clayton     Esther
2     Esther  ChemChris
3       Okon        NaN
4  ChemChris        NaN

In [43]:
comb["name"].iloc[:,0]

0      Charles
1      Clayton
2       Esther
3         Okon
4    ChemChris
Name: name, dtype: object

In [44]:
comb["name"].iloc[:,1]

0      Clayton
1       Esther
2    ChemChris
3          NaN
4          NaN
Name: name, dtype: object

In [45]:
table3=pd.DataFrame({"score":[42,56,40,68,45],"s/n":np.random.randint(30,40,5)})

In [46]:
table3

   score  s/n
0     42   33
1     56   36
2     40   32
3     68   32
4     45   31

In [47]:
table1

        name  age  isMarried
0    Charles   52       True
1    Clayton   27       True
2     Esther   40      False
3       Okon   27      False
4  ChemChris   45       True

In [48]:
pd.merge(table1,table3,left_on="age",right_on="score")

        name  age  isMarried  score  s/n
0     Esther   40      False     40   32
1  ChemChris   45       True     45   31

In [49]:
pd.merge(table1,table3,left_on="age",right_on="score",how="left")

        name  age  isMarried  score   s/n
0    Charles   52       True    NaN   NaN
1    Clayton   27       True    NaN   NaN
2     Esther   40      False   40.0  32.0
3       Okon   27      False    NaN   NaN
4  ChemChris   45       True   45.0  31.0