In [1]:
import pandas as pd

In [2]:
data1=pd.read_csv("cars.csv")

In [3]:
data1

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,Mahindra,XUV500 W8 [2015-2017],850000,2016,90300,Diesel,Manual,Surat,White,First,Individual,2179 cc,138 bhp @ 3750 rpm,330 Nm @ 1600 rpm,FWD,4585.0,1890.0,1785.0,7.0,70.0
2055,Hyundai,Eon D-Lite +,275000,2014,83000,Petrol,Manual,Ahmedabad,White,Second,Individual,814 cc,55 bhp @ 5500 rpm,75 Nm @ 4000 rpm,FWD,3495.0,1550.0,1500.0,5.0,32.0
2056,Ford,Figo Duratec Petrol ZXI 1.2,240000,2013,73000,Petrol,Manual,Thane,Silver,First,Individual,1196 cc,70 bhp @ 6250 rpm,102 Nm @ 4000 rpm,FWD,3795.0,1680.0,1427.0,5.0,45.0
2057,BMW,5-Series 520d Luxury Line [2017-2019],4290000,2018,60474,Diesel,Automatic,Coimbatore,White,First,Individual,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,RWD,4936.0,1868.0,1479.0,5.0,65.0
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],670000,2017,72000,Diesel,Manual,Guwahati,White,First,Individual,1493 cc,70 bhp @ 3600 rpm,195 Nm @ 1400 rpm,RWD,3995.0,1745.0,1880.0,7.0,NaN

In [4]:
data1=pd.read_csv("cars.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'cars.csv'

In [9]:
data1=pd.read_csv("datasets/cars.csv")

In [10]:
data1

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,Mahindra,XUV500 W8 [2015-2017],850000,2016,90300,Diesel,Manual,Surat,White,First,Individual,2179 cc,138 bhp @ 3750 rpm,330 Nm @ 1600 rpm,FWD,4585.0,1890.0,1785.0,7.0,70.0
2055,Hyundai,Eon D-Lite +,275000,2014,83000,Petrol,Manual,Ahmedabad,White,Second,Individual,814 cc,55 bhp @ 5500 rpm,75 Nm @ 4000 rpm,FWD,3495.0,1550.0,1500.0,5.0,32.0
2056,Ford,Figo Duratec Petrol ZXI 1.2,240000,2013,73000,Petrol,Manual,Thane,Silver,First,Individual,1196 cc,70 bhp @ 6250 rpm,102 Nm @ 4000 rpm,FWD,3795.0,1680.0,1427.0,5.0,45.0
2057,BMW,5-Series 520d Luxury Line [2017-2019],4290000,2018,60474,Diesel,Automatic,Coimbatore,White,First,Individual,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,RWD,4936.0,1868.0,1479.0,5.0,65.0
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],670000,2017,72000,Diesel,Manual,Guwahati,White,First,Individual,1493 cc,70 bhp @ 3600 rpm,195 Nm @ 1400 rpm,RWD,3995.0,1745.0,1880.0,7.0,NaN

In [11]:
data1.head()

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0

In [12]:
data1.tail()

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
2054,Mahindra,XUV500 W8 [2015-2017],850000,2016,90300,Diesel,Manual,Surat,White,First,Individual,2179 cc,138 bhp @ 3750 rpm,330 Nm @ 1600 rpm,FWD,4585.0,1890.0,1785.0,7.0,70.0
2055,Hyundai,Eon D-Lite +,275000,2014,83000,Petrol,Manual,Ahmedabad,White,Second,Individual,814 cc,55 bhp @ 5500 rpm,75 Nm @ 4000 rpm,FWD,3495.0,1550.0,1500.0,5.0,32.0
2056,Ford,Figo Duratec Petrol ZXI 1.2,240000,2013,73000,Petrol,Manual,Thane,Silver,First,Individual,1196 cc,70 bhp @ 6250 rpm,102 Nm @ 4000 rpm,FWD,3795.0,1680.0,1427.0,5.0,45.0
2057,BMW,5-Series 520d Luxury Line [2017-2019],4290000,2018,60474,Diesel,Automatic,Coimbatore,White,First,Individual,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,RWD,4936.0,1868.0,1479.0,5.0,65.0
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],670000,2017,72000,Diesel,Manual,Guwahati,White,First,Individual,1493 cc,70 bhp @ 3600 rpm,195 Nm @ 1400 rpm,RWD,3995.0,1745.0,1880.0,7.0,NaN

In [14]:
data1.sample(10)

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
1536,Volkswagen,Polo Highline1.2L (P),525000,2014,43550,Petrol,Manual,Hyderabad,Orange,First,Individual,1198 cc,74 bhp @ 5400 rpm,110 Nm @ 3750 rpm,FWD,3970.0,1682.0,1453.0,5.0,45.0
333,Renault,Duster RXL Petrol,600000,2017,48000,Petrol,Manual,Mumbai,Black,First,Individual,1498 cc,105 bhp @ 5600 rpm,142 Nm @ 4000 rpm,FWD,4315.0,1822.0,1695.0,5.0,50.0
1447,Audi,Q5 40 TDI Premium Plus,4475000,2020,18000,Diesel,Automatic,Delhi,White,Second,Individual,1968 cc,188 bhp @ 3800 rpm,400 Nm @ 1750 rpm,AWD,4663.0,1893.0,1659.0,5.0,70.0
395,Mercedes-Benz,M-Class ML 350 CDI,2450000,2014,65000,Diesel,Automatic,Chandigarh,White,Second,Individual,2997 cc,254 bhp @ 3600 rpm,619 Nm @ 1600 rpm,AWD,4804.0,2141.0,1796.0,5.0,70.0
1936,Honda,City CVT,185000,2008,70000,Petrol,Automatic,Lucknow,White,Second,Individual,1497 cc,78@5500,125@2700,NaN,4390.0,1690.0,1495.0,5.0,42.0
704,Honda,Jazz VX Petrol,585000,2017,24100,Petrol,Manual,Mumbai,Silver,First,Individual,1199 cc,89 bhp @ 6000 rpm,110 Nm @ 4800 rpm,FWD,3955.0,1694.0,1544.0,5.0,40.0
181,Toyota,Fortuner 3.0 4x4 MT,1675000,2014,211000,Diesel,Manual,Jaipur,White,First,Individual,2982 cc,169 bhp @ 3600 rpm,343 Nm @ 1400 rpm,AWD,4705.0,1840.0,1850.0,7.0,80.0
177,Maruti Suzuki,Wagon R VXi,350000,2013,45000,Petrol,Manual,Pune,White,First,Individual,998 cc,68@6200,90@3500,NaN,3539.0,1495.0,1700.0,5.0,35.0
1406,Hyundai,Grand i10 Asta 1.2 Kappa VTVT [2013-2016],409999,2014,55000,Petrol,Manual,Delhi,Silver,First,Individual,1197 cc,81 bhp @ 6000 rpm,114 Nm @ 4000 rpm,FWD,3765.0,1660.0,1520.0,5.0,43.0
351,Mahindra,Thar AX 4-STR Convertible Petrol MT,1700000,2021,3813,Petrol,Manual,Chennai,Red,First,Individual,1997 cc,150 bhp @ 5000 rpm,300 Nm @ 1250 rpm,AWD,3985.0,1820.0,1855.0,4.0,57.0

In [16]:
data1.head(7)

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0
5,Maruti Suzuki,Ciaz ZXi,675000,2017,73315,Petrol,Manual,Pune,Grey,First,Individual,1373 cc,91 bhp @ 6000 rpm,130 Nm @ 4000 rpm,FWD,4490.0,1730.0,1485.0,5.0,43.0
6,Mercedes-Benz,CLA 200 Petrol Sport,1898999,2015,47000,Petrol,Automatic,Mumbai,White,Second,Individual,1991 cc,181 bhp @ 5500 rpm,300 Nm @ 1200 rpm,FWD,4630.0,1777.0,1432.0,5.0,NaN

In [17]:
data1.columns

Index(['Make', 'Model', 'Price', 'Year', 'Kilometer', 'Fuel Type',
       'Transmission', 'Location', 'Color', 'Owner', 'Seller Type', 'Engine',
       'Max Power', 'Max Torque', 'Drivetrain', 'Length', 'Width', 'Height',
       'Seating Capacity', 'Fuel Tank Capacity'],
      dtype='object')

In [ ]:
data1.rename(columns={"Price":"Car_Price"})

,Make,Model,Car_Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,Mahindra,XUV500 W8 [2015-2017],850000,2016,90300,Diesel,Manual,Surat,White,First,Individual,2179 cc,138 bhp @ 3750 rpm,330 Nm @ 1600 rpm,FWD,4585.0,1890.0,1785.0,7.0,70.0
2055,Hyundai,Eon D-Lite +,275000,2014,83000,Petrol,Manual,Ahmedabad,White,Second,Individual,814 cc,55 bhp @ 5500 rpm,75 Nm @ 4000 rpm,FWD,3495.0,1550.0,1500.0,5.0,32.0
2056,Ford,Figo Duratec Petrol ZXI 1.2,240000,2013,73000,Petrol,Manual,Thane,Silver,First,Individual,1196 cc,70 bhp @ 6250 rpm,102 Nm @ 4000 rpm,FWD,3795.0,1680.0,1427.0,5.0,45.0
2057,BMW,5-Series 520d Luxury Line [2017-2019],4290000,2018,60474,Diesel,Automatic,Coimbatore,White,First,Individual,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,RWD,4936.0,1868.0,1479.0,5.0,65.0
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],670000,2017,72000,Diesel,Manual,Guwahati,White,First,Individual,1493 cc,70 bhp @ 3600 rpm,195 Nm @ 1400 rpm,RWD,3995.0,1745.0,1880.0,7.0,NaN

In [19]:
data1

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,Mahindra,XUV500 W8 [2015-2017],850000,2016,90300,Diesel,Manual,Surat,White,First,Individual,2179 cc,138 bhp @ 3750 rpm,330 Nm @ 1600 rpm,FWD,4585.0,1890.0,1785.0,7.0,70.0
2055,Hyundai,Eon D-Lite +,275000,2014,83000,Petrol,Manual,Ahmedabad,White,Second,Individual,814 cc,55 bhp @ 5500 rpm,75 Nm @ 4000 rpm,FWD,3495.0,1550.0,1500.0,5.0,32.0
2056,Ford,Figo Duratec Petrol ZXI 1.2,240000,2013,73000,Petrol,Manual,Thane,Silver,First,Individual,1196 cc,70 bhp @ 6250 rpm,102 Nm @ 4000 rpm,FWD,3795.0,1680.0,1427.0,5.0,45.0
2057,BMW,5-Series 520d Luxury Line [2017-2019],4290000,2018,60474,Diesel,Automatic,Coimbatore,White,First,Individual,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,RWD,4936.0,1868.0,1479.0,5.0,65.0
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],670000,2017,72000,Diesel,Manual,Guwahati,White,First,Individual,1493 cc,70 bhp @ 3600 rpm,195 Nm @ 1400 rpm,RWD,3995.0,1745.0,1880.0,7.0,NaN

In [20]:
data1.rename(index={0:"Esther",3:"Charles"})

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
Esther,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
Charles,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,Mahindra,XUV500 W8 [2015-2017],850000,2016,90300,Diesel,Manual,Surat,White,First,Individual,2179 cc,138 bhp @ 3750 rpm,330 Nm @ 1600 rpm,FWD,4585.0,1890.0,1785.0,7.0,70.0
2055,Hyundai,Eon D-Lite +,275000,2014,83000,Petrol,Manual,Ahmedabad,White,Second,Individual,814 cc,55 bhp @ 5500 rpm,75 Nm @ 4000 rpm,FWD,3495.0,1550.0,1500.0,5.0,32.0
2056,Ford,Figo Duratec Petrol ZXI 1.2,240000,2013,73000,Petrol,Manual,Thane,Silver,First,Individual,1196 cc,70 bhp @ 6250 rpm,102 Nm @ 4000 rpm,FWD,3795.0,1680.0,1427.0,5.0,45.0
2057,BMW,5-Series 520d Luxury Line [2017-2019],4290000,2018,60474,Diesel,Automatic,Coimbatore,White,First,Individual,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,RWD,4936.0,1868.0,1479.0,5.0,65.0
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],670000,2017,72000,Diesel,Manual,Guwahati,White,First,Individual,1493 cc,70 bhp @ 3600 rpm,195 Nm @ 1400 rpm,RWD,3995.0,1745.0,1880.0,7.0,NaN

In [21]:
data1.shape

(2059, 20)

In [23]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2059 entries, 0 to 2058
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Make                2059 non-null   object
 1   Model               2059 non-null   object
 2   Price               2059 non-null   int64
 3   Year                2059 non-null   int64
 4   Kilometer           2059 non-null   int64
 5   Fuel Type           2059 non-null   object
 6   Transmission        2059 non-null   object
 7   Location            2059 non-null   object
 8   Color               2059 non-null   object
 9   Owner               2059 non-null   object
 10  Seller Type         2059 non-null   object
 11  Engine              1979 non-null   object
 12  Max Power           1979 non-null   object
 13  Max Torque          1979 non-null   object
 14  Drivetrain          1923 non-null   object
 15  Length              1995 non-null   float64
 16  Width               1995 non-null   float64
 17  Height              1995 non-null   float64
 18  Seating Capacity    1995 non-null   float64
 19  Fuel Tank Capacity  1946 non-null   float64
dtypes: float64(5), int64(3), object(12)
memory usage: 321.8+ KB

In [24]:
data1.describe()

,Price,Year,Kilometer,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
count,2.059000e+03,2059.000000,2.059000e+03,1995.000000,1995.000000,1995.000000,1995.000000,1946.000000
mean,1.702992e+06,2016.425449,5.422471e+04,4280.860652,1767.991980,1591.735338,5.306266,52.002210
std,2.419881e+06,3.363564,5.736172e+04,442.458507,135.265825,136.073956,0.822170,15.110198
min,4.900000e+04,1988.000000,0.000000e+00,3099.000000,1475.000000,1165.000000,2.000000,15.000000
25%,4.849990e+05,2014.000000,2.900000e+04,3985.000000,1695.000000,1485.000000,5.000000,41.250000
50%,8.250000e+05,2017.000000,5.000000e+04,4370.000000,1770.000000,1545.000000,5.000000,50.000000
75%,1.925000e+06,2019.000000,7.200000e+04,4629.000000,1831.500000,1675.000000,5.000000,60.000000
max,3.500000e+07,2022.000000,2.000000e+06,5569.000000,2220.000000,1995.000000,8.000000,105.000000

In [25]:
data1.describe(include=["object"])

,Make,Model,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain
count,2059,2059,2059,2059,2059,2059,2059,2059,1979,1979,1979,1923
unique,33,1050,9,2,77,17,6,3,108,335,290,3
top,Maruti Suzuki,X1 sDrive20d xLine,Diesel,Manual,Mumbai,White,First,Individual,1197 cc,89 bhp @ 4000 rpm,200 Nm @ 1750 rpm,FWD
freq,440,15,1049,1133,342,802,1619,1997,231,90,90,1330

In [26]:
data1.describe(include=["object","int","float"])

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
count,2059,2059,2.059000e+03,2059.000000,2.059000e+03,2059,2059,2059,2059,2059,2059,1979,1979,1979,1923,1995.000000,1995.000000,1995.000000,1995.000000,1946.000000
unique,33,1050,NaN,NaN,NaN,9,2,77,17,6,3,108,335,290,3,NaN,NaN,NaN,NaN,NaN
top,Maruti Suzuki,X1 sDrive20d xLine,NaN,NaN,NaN,Diesel,Manual,Mumbai,White,First,Individual,1197 cc,89 bhp @ 4000 rpm,200 Nm @ 1750 rpm,FWD,NaN,NaN,NaN,NaN,NaN
freq,440,15,NaN,NaN,NaN,1049,1133,342,802,1619,1997,231,90,90,1330,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,1.702992e+06,2016.425449,5.422471e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4280.860652,1767.991980,1591.735338,5.306266,52.002210
std,NaN,NaN,2.419881e+06,3.363564,5.736172e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,442.458507,135.265825,136.073956,0.822170,15.110198
min,NaN,NaN,4.900000e+04,1988.000000,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3099.000000,1475.000000,1165.000000,2.000000,15.000000
25%,NaN,NaN,4.849990e+05,2014.000000,2.900000e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3985.000000,1695.000000,1485.000000,5.000000,41.250000
50%,NaN,NaN,8.250000e+05,2017.000000,5.000000e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4370.000000,1770.000000,1545.000000,5.000000,50.000000
75%,NaN,NaN,1.925000e+06,2019.000000,7.200000e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4629.000000,1831.500000,1675.000000,5.000000,60.000000
max,NaN,NaN,3.500000e+07,2022.000000,2.000000e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5569.000000,2220.000000,1995.000000,8.000000,105.000000

## Indexing,slicing(Filtering)

In [27]:
data1["Make"]

0               Honda
1       Maruti Suzuki
2             Hyundai
3              Toyota
4              Toyota
            ...
2054         Mahindra
2055          Hyundai
2056             Ford
2057              BMW
2058         Mahindra
Name: Make, Length: 2059, dtype: object

In [29]:
data1["Engine"]

0       1198 cc
1       1248 cc
2       1197 cc
3       1197 cc
4       2393 cc
         ...
2054    2179 cc
2055     814 cc
2056    1196 cc
2057    1995 cc
2058    1493 cc
Name: Engine, Length: 2059, dtype: object

In [30]:
data1.Make

0               Honda
1       Maruti Suzuki
2             Hyundai
3              Toyota
4              Toyota
            ...
2054         Mahindra
2055          Hyundai
2056             Ford
2057              BMW
2058         Mahindra
Name: Make, Length: 2059, dtype: object

In [31]:
data1.Location

0             Pune
1         Ludhiana
2          Lucknow
3        Mangalore
4           Mumbai
           ...
2054         Surat
2055     Ahmedabad
2056         Thane
2057    Coimbatore
2058      Guwahati
Name: Location, Length: 2059, dtype: object

In [34]:
data1.Transmission

0          Manual
1          Manual
2          Manual
3          Manual
4          Manual
          ...
2054       Manual
2055       Manual
2056       Manual
2057    Automatic
2058       Manual
Name: Transmission, Length: 2059, dtype: object

In [36]:
data1.Transmission.unique()

array(['Manual', 'Automatic'], dtype=object)

In [38]:
data1.columns

Index(['Make', 'Model', 'Price', 'Year', 'Kilometer', 'Fuel Type',
       'Transmission', 'Location', 'Color', 'Owner', 'Seller Type', 'Engine',
       'Max Power', 'Max Torque', 'Drivetrain', 'Length', 'Width', 'Height',
       'Seating Capacity', 'Fuel Tank Capacity'],
      dtype='object')

In [40]:
data1["Fuel Type"].unique()

array(['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric', 'CNG + CNG',
       'Hybrid', 'Petrol + CNG', 'Petrol + LPG'], dtype=object)

In [41]:
data1["Fuel Type"].unique().size

9

In [42]:
data1.loc[0]

Make                                Honda
Model                 Amaze 1.2 VX i-VTEC
Price                              505000
Year                                 2017
Kilometer                           87150
Fuel Type                          Petrol
Transmission                       Manual
Location                             Pune
Color                                Grey
Owner                               First
Seller Type                     Corporate
Engine                            1198 cc
Max Power               87 bhp @ 6000 rpm
Max Torque              109 Nm @ 4500 rpm
Drivetrain                            FWD
Length                             3990.0
Width                              1680.0
Height                             1505.0
Seating Capacity                      5.0
Fuel Tank Capacity                   35.0
Name: 0, dtype: object

In [44]:
data1[0]

KeyError: 0

In [43]:
data1.head(2)

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0

In [47]:
data1.loc[20]

Make                      Maruti Suzuki
Model                  S-Presso VXi AMT
Price                            470000
Year                               2020
Kilometer                          2169
Fuel Type                        Petrol
Transmission                  Automatic
Location                         Mumbai
Color                              Grey
Owner                             First
Seller Type                  Individual
Engine                           998 cc
Max Power             67 bhp @ 5500 rpm
Max Torque             90 Nm @ 3500 rpm
Drivetrain                          FWD
Length                           3565.0
Width                            1520.0
Height                           1564.0
Seating Capacity                    5.0
Fuel Tank Capacity                 27.0
Name: 20, dtype: object

In [50]:
data1.loc[20,"Price"]

470000

In [51]:
data1.loc[[0,3,200],["Make","Price","Location","Fuel Type"]]

       Make    Price   Location Fuel Type
0     Honda   505000       Pune    Petrol
3    Toyota   799000  Mangalore    Petrol
200     BMW  2975000     Mohali    Diesel

In [52]:
data1

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,Mahindra,XUV500 W8 [2015-2017],850000,2016,90300,Diesel,Manual,Surat,White,First,Individual,2179 cc,138 bhp @ 3750 rpm,330 Nm @ 1600 rpm,FWD,4585.0,1890.0,1785.0,7.0,70.0
2055,Hyundai,Eon D-Lite +,275000,2014,83000,Petrol,Manual,Ahmedabad,White,Second,Individual,814 cc,55 bhp @ 5500 rpm,75 Nm @ 4000 rpm,FWD,3495.0,1550.0,1500.0,5.0,32.0
2056,Ford,Figo Duratec Petrol ZXI 1.2,240000,2013,73000,Petrol,Manual,Thane,Silver,First,Individual,1196 cc,70 bhp @ 6250 rpm,102 Nm @ 4000 rpm,FWD,3795.0,1680.0,1427.0,5.0,45.0
2057,BMW,5-Series 520d Luxury Line [2017-2019],4290000,2018,60474,Diesel,Automatic,Coimbatore,White,First,Individual,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,RWD,4936.0,1868.0,1479.0,5.0,65.0
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],670000,2017,72000,Diesel,Manual,Guwahati,White,First,Individual,1493 cc,70 bhp @ 3600 rpm,195 Nm @ 1400 rpm,RWD,3995.0,1745.0,1880.0,7.0,NaN

In [53]:
data1.Year==2017

0        True
1       False
2       False
3       False
4       False
        ...
2054    False
2055    False
2056    False
2057    False
2058     True
Name: Year, Length: 2059, dtype: bool

In [54]:
data1[data1.Year==2017]

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
5,Maruti Suzuki,Ciaz ZXi,675000,2017,73315,Petrol,Manual,Pune,Grey,First,Individual,1373 cc,91 bhp @ 6000 rpm,130 Nm @ 4000 rpm,FWD,4490.0,1730.0,1485.0,5.0,43.0
7,BMW,X1 xDrive20d M Sport,2650000,2017,75000,Diesel,Automatic,Coimbatore,White,Second,Individual,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,AWD,4439.0,1821.0,1612.0,5.0,51.0
8,Skoda,Octavia 1.8 TSI Style Plus AT [2017],1390000,2017,56000,Petrol,Automatic,Mumbai,White,First,Individual,1798 cc,177 bhp @ 5100 rpm,250 Nm @ 1250 rpm,FWD,4670.0,1814.0,1476.0,5.0,50.0
10,Hyundai,Elite i20 Sportz 1.2,591000,2017,20281,Petrol,Manual,Mumbai,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,115 Nm @ 4000 rpm,FWD,3985.0,1734.0,1505.0,5.0,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1998,Maruti Suzuki,Ciaz Alpha 1.4 AT,725000,2017,55000,Petrol,Automatic,Noida,White,First,Individual,1373 cc,91 bhp @ 6000 rpm,130 Nm @ 4000 rpm,FWD,4490.0,1730.0,1485.0,5.0,43.0
1999,Hyundai,Grand i10 Sportz 1.2 Kappa VTVT [2016-2017],400000,2017,35000,Petrol,Manual,Kolkata,Blue,First,Individual,1197 cc,81 bhp @ 6000 rpm,114 Nm @ 4000 rpm,FWD,3765.0,1660.0,1520.0,5.0,43.0
2010,Audi,A4 30 TFSI Technology Pack,3000000,2017,42000,Petrol,Automatic,Pune,White,First,Individual,1395 cc,148 bhp @ 5000 rpm,250 Nm @ 1500 rpm,FWD,4726.0,1842.0,1427.0,5.0,54.0
2049,Mercedes-Benz,GLS 400 4MATIC,5950000,2017,80000,Petrol,Automatic,Delhi,Black,First,Individual,2996 cc,329 bhp @ 5250 rpm,480 Nm @ 1600 rpm,AWD,5130.0,1934.0,1850.0,5.0,100.0
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],670000,2017,72000,Diesel,Manual,Guwahati,White,First,Individual,1493 cc,70 bhp @ 3600 rpm,195 Nm @ 1400 rpm,RWD,3995.0,1745.0,1880.0,7.0,NaN

In [55]:
data1

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,Mahindra,XUV500 W8 [2015-2017],850000,2016,90300,Diesel,Manual,Surat,White,First,Individual,2179 cc,138 bhp @ 3750 rpm,330 Nm @ 1600 rpm,FWD,4585.0,1890.0,1785.0,7.0,70.0
2055,Hyundai,Eon D-Lite +,275000,2014,83000,Petrol,Manual,Ahmedabad,White,Second,Individual,814 cc,55 bhp @ 5500 rpm,75 Nm @ 4000 rpm,FWD,3495.0,1550.0,1500.0,5.0,32.0
2056,Ford,Figo Duratec Petrol ZXI 1.2,240000,2013,73000,Petrol,Manual,Thane,Silver,First,Individual,1196 cc,70 bhp @ 6250 rpm,102 Nm @ 4000 rpm,FWD,3795.0,1680.0,1427.0,5.0,45.0
2057,BMW,5-Series 520d Luxury Line [2017-2019],4290000,2018,60474,Diesel,Automatic,Coimbatore,White,First,Individual,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,RWD,4936.0,1868.0,1479.0,5.0,65.0
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],670000,2017,72000,Diesel,Manual,Guwahati,White,First,Individual,1493 cc,70 bhp @ 3600 rpm,195 Nm @ 1400 rpm,RWD,3995.0,1745.0,1880.0,7.0,NaN

In [57]:
data1.Price>5000000

0       False
1       False
2       False
3       False
4       False
        ...
2054    False
2055    False
2056    False
2057    False
2058    False
Name: Price, Length: 2059, dtype: bool

In [58]:
data1[data1.Price>5000000]

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
95,Porsche,Cayenne Coupe Platinum Edition,16200000,2022,2766,Petrol,Automatic,Mumbai,Blue,First,Individual,2995 cc,335 bhp @ 5300 rpm,450 Nm @ 1340 rpm,AWD,4931.0,1983.0,1676.0,4.0,75.0
96,Mercedes-Benz,C-Class Cabriolet C 300,5100000,2017,56000,Petrol,Automatic,Ghaziabad,White,Second,Individual,1991 cc,241 bhp @ 5500 rpm,370 Nm @ 1300 rpm,RWD,4686.0,1810.0,1409.0,4.0,59.0
139,Audi,Q5 45 TFSI Premium Plus,5651000,2022,1,Petrol,Automatic,Delhi,Blue,UnRegistered Car,Individual,1984 cc,248 bhp @ 5000 rpm,370 Nm @ 1600 rpm,AWD,4663.0,1898.0,1659.0,5.0,70.0
156,Land Rover,Discovery Sport S,6500000,2020,6000,Diesel,Automatic,Hyderabad,White,First,Individual,1999 cc,177 bhp @ 4000 rpm,430 Nm @ 1750 rpm,AWD,4600.0,2069.0,1724.0,7.0,70.0
160,Mercedes-Benz,S-Class Maybach S 500,11500000,2016,27000,Petrol,Automatic,Delhi,Blue,First,Individual,4663 cc,453 bhp @ 5250 rpm,700 Nm @ 1800 rpm,RWD,5453.0,1899.0,1498.0,4.0,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1979,BMW,X5 xDrive 30d M Sport,5500000,2017,68690,Diesel,Automatic,Hyderabad,Blue,First,Corporate,2993 cc,258 bhp @ 4000 rpm,560 Nm @ 1500 rpm,AWD,4886.0,1938.0,1762.0,5.0,NaN
2007,Mercedes-Benz,E-Class E 220d Exclusive [2019-2019],6100000,2020,9500,Diesel,Automatic,Mumbai,Silver,First,Corporate,1950 cc,192 bhp @ 3800 rpm,400 Nm @ 1600 rpm,RWD,5063.0,1860.0,1494.0,5.0,80.0
2012,BMW,X3 xDrive 20d Luxury Line [2018-2020],6200000,2021,39000,Diesel,Automatic,Ahmedabad,White,First,Individual,1995 cc,190 bhp @ 4000 rpm,400 Nm @ 1750 rpm,AWD,4657.0,1881.0,1678.0,5.0,67.0
2032,Land Rover,Range Rover Velar 2.0 S Petrol 250,8900000,2020,88000,Petrol,Automatic,Mumbai,White,First,Individual,1997 cc,247 bhp @ 5500 rpm,365 Nm @ 1500 rpm,AWD,4797.0,2032.0,1665.0,5.0,NaN
2049,Mercedes-Benz,GLS 400 4MATIC,5950000,2017,80000,Petrol,Automatic,Delhi,Black,First,Individual,2996 cc,329 bhp @ 5250 rpm,480 Nm @ 1600 rpm,AWD,5130.0,1934.0,1850.0,5.0,100.0

In [59]:
data1.Price<6000000

0       True
1       True
2       True
3       True
4       True
        ...
2054    True
2055    True
2056    True
2057    True
2058    True
Name: Price, Length: 2059, dtype: bool

In [ ]:
data1[data1.Price<6000000]

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,Mahindra,XUV500 W8 [2015-2017],850000,2016,90300,Diesel,Manual,Surat,White,First,Individual,2179 cc,138 bhp @ 3750 rpm,330 Nm @ 1600 rpm,FWD,4585.0,1890.0,1785.0,7.0,70.0
2055,Hyundai,Eon D-Lite +,275000,2014,83000,Petrol,Manual,Ahmedabad,White,Second,Individual,814 cc,55 bhp @ 5500 rpm,75 Nm @ 4000 rpm,FWD,3495.0,1550.0,1500.0,5.0,32.0
2056,Ford,Figo Duratec Petrol ZXI 1.2,240000,2013,73000,Petrol,Manual,Thane,Silver,First,Individual,1196 cc,70 bhp @ 6250 rpm,102 Nm @ 4000 rpm,FWD,3795.0,1680.0,1427.0,5.0,45.0
2057,BMW,5-Series 520d Luxury Line [2017-2019],4290000,2018,60474,Diesel,Automatic,Coimbatore,White,First,Individual,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,RWD,4936.0,1868.0,1479.0,5.0,65.0
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],670000,2017,72000,Diesel,Manual,Guwahati,White,First,Individual,1493 cc,70 bhp @ 3600 rpm,195 Nm @ 1400 rpm,RWD,3995.0,1745.0,1880.0,7.0,NaN

In [64]:
(data1.Price>5000000) & (data1.Price<6000000)

0       False
1       False
2       False
3       False
4       False
        ...
2054    False
2055    False
2056    False
2057    False
2058    False
Name: Price, Length: 2059, dtype: bool

In [67]:
data1[(data1.Price>6000000) & (data1.Price<7000000)]

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
156,Land Rover,Discovery Sport S,6500000,2020,6000,Diesel,Automatic,Hyderabad,White,First,Individual,1999 cc,177 bhp @ 4000 rpm,430 Nm @ 1750 rpm,AWD,4600.0,2069.0,1724.0,7.0,70.0
371,Mercedes-Benz,C-Class Cabriolet C 300,6500000,2020,21000,Petrol,Automatic,Gurgaon,White,Second,Individual,1991 cc,241 bhp @ 5500 rpm,370 Nm @ 1300 rpm,RWD,4686.0,1810.0,1409.0,4.0,59.0
479,Mercedes-Benz,GLC 220d 4MATIC Progressive,6400000,2022,5500,Diesel,Automatic,Hyderabad,White,UnRegistered Car,Individual,1950 cc,192 bhp @ 3800 rpm,400 Nm @ 1600 rpm,AWD,4658.0,1890.0,1644.0,5.0,66.0
525,BMW,7-Series 730Ld M Sport,6900000,2017,42200,Diesel,Automatic,Mumbai,Black,First,Individual,2993 cc,262 bhp @ 4000 rpm,620 Nm @ 2000 rpm,RWD,5219.0,1902.0,1481.0,4.0,78.0
595,Mercedes-Benz,E-Class E 200 Exclusive [2019-2019],6500000,2021,7500,Petrol,Automatic,Delhi,Black,First,Individual,1991 cc,194 bhp @ 5800 rpm,300 Nm @ 1600 rpm,RWD,5063.0,1860.0,1494.0,5.0,80.0
611,Mercedes-Benz,GLC 200 Progressive,6975000,2022,2000,Petrol,Automatic,Karnal,White,First,Individual,1991 cc,194 bhp @ 5500 rpm,320 Nm @ 1650 rpm,RWD,4658.0,1890.0,1644.0,5.0,66.0
726,Mercedes-Benz,E-Class E 350 d Exclusive [2017-2019],6225000,2019,42079,Diesel,Automatic,Pune,Silver,First,Individual,2987 cc,255 bhp @ 3400 rpm,620 Nm @ 1600 rpm,RWD,5063.0,1860.0,1494.0,5.0,80.0
789,Mercedes-Benz,GLC 220d 4MATIC Progressive [2019-2021],6800000,2020,14500,Diesel,Automatic,Pune,Silver,First,Individual,1950 cc,192 bhp @ 3800 rpm,400 Nm @ 1600 rpm,AWD,4658.0,1890.0,1644.0,5.0,66.0
811,Mercedes-Benz,E-Class E 220 d Avantgarde,6500000,2019,5750,Diesel,Automatic,Bangalore,White,First,Individual,1950 cc,192 bhp @ 3800 rpm,400 Nm @ 1600 rpm,RWD,5063.0,1860.0,1494.0,5.0,80.0
837,Porsche,Panamera 3.0 Diesel,6350000,2016,20500,Diesel,Automatic,Delhi,White,First,Corporate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
840,Mercedes-Benz,GLS 350 d,6875000,2019,53000,Diesel,Automatic,Dehradun,White,First,Individual,2987 cc,255 bhp @ 3400 rpm,620 Nm @ 1600 rpm,AWD,5130.0,1934.0,1850.0,7.0,100.0
857,Audi,Q7 45 TDI Technology Pack,6700000,2018,39850,Diesel,Automatic,Surat,Blue,First,Individual,2967 cc,245 bhp @ 2910 rpm,600 Nm @ 1500 rpm,AWD,5052.0,1968.0,1740.0,7.0,75.0
1008,Mercedes-Benz,GLC 200 Progressive,6600000,2021,16785,Petrol,Automatic,Bangalore,White,First,Individual,1991 cc,194 bhp @ 5500 rpm,320 Nm @ 1650 rpm,RWD,4658.0,1890.0,1644.0,5.0,66.0
1128,Mercedes-Benz,GLE 350 d,6150000,2018,18000,Diesel,Automatic,Chandigarh,Black,First,Individual,2987 cc,255 bhp @ 3400 rpm,620 Nm @ 1600 rpm,AWD,4819.0,2141.0,1796.0,5.0,93.0
1166,BMW,X4 xDrive30d M Sport X [2019-2020],6100000,2021,24500,Diesel,Automatic,Mumbai,Red,First,Corporate,2993 cc,260 bhp @ 4000 rpm,620 Nm @ 2000 rpm,AWD,4752.0,1918.0,1621.0,5.0,68.0
1196,BMW,5-Series 520d Luxury Line [2017-2019],6390000,2022,6000,Diesel,Automatic,Mumbai,Grey,First,Individual,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,RWD,4936.0,1868.0,1479.0,5.0,65.0
1309,Land Rover,Discovery Sport HSE Luxury 7-Seater,6900000,2020,32368,Diesel,Automatic,Chennai,White,First,Individual,2179 cc,188 bhp @ 3500 rpm,420 Nm @ 1750 rpm,AWD,4600.0,2069.0,1724.0,7.0,65.0
1348,Land Rover,Evoque SE Dynamic,6500000,2021,12000,Diesel,Automatic,Hyderabad,White,First,Individual,1999 cc,177 bhp @ 4000 rpm,430 Nm @ 1750 rpm,AWD,4360.0,2120.0,1635.0,5.0,57.0
1411,BMW,X3 xDrive 20d Luxury Line [2018-2020],6800000,2022,33000,Diesel,Automatic,Chennai,White,First,Individual,1995 cc,190 bhp @ 4000 rpm,400 Nm @ 1750 rpm,AWD,4657.0,1881.0,1678.0,5.0,67.0
1451,Mercedes-Benz,GLC 220d 4MATIC Progressive,6750000,2022,7000,Diesel,Automatic,Lucknow,Blue,First,Individual,1950 cc,192 bhp @ 3800 rpm,400 Nm @ 1600 rpm,AWD,4658.0,1890.0,1644.0,5.0,66.0
1563,Mercedes-Benz,C-Class C220d Progressive,6100000,2022,500,Diesel,Automatic,Delhi,Grey,First,Individual,1950 cc,192 bhp @ 3800 rpm,400 Nm @ 1600 rpm,RWD,4686.0,1810.0,1442.0,5.0,66.0
1600,Mercedes-Benz,GLC 220d 4MATIC Progressive [2019-2021],6500000,2020,13000,Diesel,Automatic,Mumbai,Silver,First,Individual,1950 cc,192 bhp @ 3800 rpm,400 Nm @ 1600 rpm,AWD,4658.0,1890.0,1644.0,5.0,66.0
1657,Jeep,Wrangler Rubicon,6100000,2022,15000,Petrol,Automatic,Mumbai,Red,First,Individual,1995 cc,268 bhp @ 5150 rpm,400 Nm @ 3000 rpm,AWD,4882.0,1894.0,1848.0,5.0,81.0
1727,Mercedes-Benz,CLS 300d [2018-2019],6975000,2020,15200,Diesel,Automatic,Delhi,White,First,Individual,1950 cc,241 bhp @ 4200 rpm,500 Nm @ 1600 rpm,RWD,4988.0,1890.0,1435.0,5.0,66.0
1731,Mercedes-Benz,V-Class Elite LWB,6300000,2020,40000,Diesel,Automatic,Delhi,Silver,First,Corporate,1950 cc,161 bhp @ 4200 rpm,380 Nm @ 1200 rpm,RWD,5140.0,1928.0,1901.0,6.0,57.0
1749,BMW,X3 xDrive30i M Sport,6680000,2022,18223,Petrol,Automatic,Ahmedabad,Blue,First,Individual,1998 cc,248 bhp @ 5200 rpm,350 Nm @ 1450 rpm,AWD,4708.0,1891.0,1676.0,5.0,60.0
2007,Mercedes-Benz,E-Class E 220d Exclusive [2019-2019],6100000,2020,9500,Diesel,Automatic,Mumbai,Silver,First,Corporate,1950 cc,192 bhp @ 3800 rpm,400 Nm @ 1600 rpm,RWD,5063.0,1860.0,1494.0,5.0,80.0
2012,BMW,X3 xDrive 20d Luxury Line [2018-2020],6200000,2021,39000,Diesel,Automatic,Ahmedabad,White,First,Individual,1995 cc,190 bhp @ 4000 rpm,400 Nm @ 1750 rpm,AWD,4657.0,1881.0,1678.0,5.0,67.0

In [68]:
data1[(data1.Price>6000000) & (data1.Price<7000000)].shape

(28, 20)

In [70]:
data1[(data1.Price>6000000) & (data1.Price<7000000)].Make.unique()

array(['Land Rover', 'Mercedes-Benz', 'BMW', 'Porsche', 'Audi', 'Jeep'],
      dtype=object)